// apps/partymatch/app/app.vue
<script setup>
import {
	ElectionNavbar,
	ElectionButton,
	ElectionSharer,
	ElectionAboutActions,
	ElectionFooter,
} from '@election/ui/vue';
</script>

<template>
	<div class="flex flex-col gap-6">
		<ElectionNavbar />
		<h1 class="text-h1 font-sriracha text-center font-bold underline">
			Party Match!
		</h1>

		<ElectionButton class="typo-h9 font-kondolar self-center font-bold"
			>เริ่มเลอ</ElectionButton
		>
		<ElectionAboutActions dataUrl="#" />
		<ElectionSharer />
		<ElectionFooter />
	</div>
</template>

// apps/politicalflashback/app/page.tsx
import {
	ElectionNavbar,
	ElectionButton,
	ElectionSharer,
	ElectionAboutActions,
	ElectionFooter,
} from '@election/ui/react';

export default function Home() {
	return (
		<div className="flex flex-col gap-6">
			<ElectionNavbar />
			<h1 className="text-h1 font-sriracha text-center font-bold underline">
				Political Flashback!
			</h1>

			<ElectionButton className="typo-h9 font-kondolar self-center font-bold">
				เริ่มเลอ
			</ElectionButton>
			<ElectionAboutActions dataUrl="#" />
			<ElectionSharer />
			<ElectionFooter />
		</div>
	);
}
