// apps/promisedeconstructed/src/app/page.tsx
export default function Home() {
	return (
		<main>
			<header className="flex flex-col gap-4 py-5 md:py-10">
				<div className="mx-auto flex w-[85svw] max-w-[600px] flex-col gap-2 text-center">
					<p className="text-purple-1 font-sriracha text-h7">
						Promise Deconstructed
					</p>
					<h1 className="text-h3 font-kondolar font-bold">
						ถอดโครงสร้างสัญญาพรรคการเมือง
					</h1>
				</div>
			</header>
		</main>
	);
}

// apps/partymatch/app/app.vue
<script setup>
import {
	ElectionNavbar,
	ElectionButton,
	ElectionSharer,
	ElectionAboutActions,
	ElectionFooter,
} from '@election/ui/vue';
</script>

<template>
	<div class="flex flex-col gap-6">
		<ElectionNavbar />
		<h1 class="text-h1 font-sriracha text-center font-bold underline">
			Party Match!
		</h1>

		<ElectionButton class="typo-h9 font-kondolar self-center font-bold"
			>เริ่มเลอ</ElectionButton
		>
		<ElectionAboutActions dataUrl="#" />
		<ElectionSharer />
		<ElectionFooter />
	</div>
</template>
