// apps/partymatch/app/pages/about.vue
<script setup>
import {
	ElectionNavbar,
	ElectionButton,
	ElectionSharer,
	ElectionAboutActions,
	ElectionFooter,
} from '@election/ui/vue';

const team = [
	{
		role: 'ออกแบบและพัฒนาเว็บไซต์',
		names: ['มนสิชา ศรีสวนแตง'],
		links: ['https://monsicha.info/'],
	},
	{
		role: 'ที่ปรึกษาพัฒนาเว็บไซต์',
		names: ['วิถี ภูษิตาสัย'],
		links: ['https://github.com/Th1nkK1D'],
	},
	{
		role: 'จัดการข้อมูล',
		names: ['ปฏิภาณ ศรีชัย'],
		links: ['https://www.linkedin.com/in/patiphan-srichai-8b6916275/'],
	},
	{
		role: 'สืบค้นและเรียบเรียงข้อมูล',
		names: ['อาลาวีย์ วาแม'],
		links: ['https://www.linkedin.com/in/alawee-wamae/'],
	},
	{
		role: 'บรรณาธิการ',
		names: ['ธนิสรา เรืองเดช', 'น้ำใส ศุภวงศ์'],
		links: [
			'https://www.linkedin.com/in/thanisara-r/',
			'https://www.instagram.com/namsaisupavong/',
		],
	},
];
</script>

<template>
	<div class="flex flex-col gap-8">
		<ElectionNavbar />
		<h1 class="text-h3 font-kondolar py-10 text-center font-bold">
			เกี่ยวกับโครงการ
		</h1>

		<div class="section flex flex-col gap-2">
			<h2 class="text-h5 font-kondolar font-bold">เป้าหมาย</h2>
			<p>
				ตลอดระยะเวลา 3 ปี นับแต่การเลือกตั้งในปี 2566 สมาชิกสภาผู้แทนราษฎร (สส.)
				ในฐานะผู้แทนที่เราเลือกไปทำงานในรัฐสภา
				ได้ผลักดันร่างกฎหมายและนโยบายที่กระทบกับชีวิตของเราโดยตรง
				โดยผู้แทนเหล่านี้ตัดสินใจลงมติเหล่านั้นจาก ‘มติพรรค’ ที่ตัวเองสังกัด
				WeVis จึงได้รวบรวมข้อมูลการลงมติของสมาชิกรัฐสภาในโปรเจกต์
				<a
					href="https://parliamentwatch.wevis.info/"
					class="hover:text-purple-1 underline"
					target="_blank"
					rel="noopener noreferrer"
					>Parliament Watch</a
				>
				เพื่อให้ประชาชนได้ตรวจสอบการทำงานของ สส.
				และพรรคการเมืองที่เราเลือกว่าได้ทำอะไร
				และดำเนินนโยบายตามที่ได้สัญญาไว้กับประชาชนหรือไม่ ก่อนเข้าคูหาในสนาม
				#เลือกตั้ง69 WeVis ขอชวนประชาชนผู้มีสิทธิเลือกตั้ง
				ย้อนดูว่าพรรคที่คุณเคยเลือกให้ทำงานในสภาชุดก่อนหน้า ทำงานตรงใจคุณแค่ไหน
				? แม้ประเด็นที่คัดเลือกมาให้โหวต
				อาจเป็นเพียงส่วนหนึ่งของประเด็นที่ถูกผลักดันในสภาตลอด 3 ปีที่ผ่านมา
				แต่ก็ชวนคิดว่าพรรคการเมืองที่เราเคยเลือก
				ได้ทำหน้าที่อย่างที่เราคาดหวังไว้หรือไม่ และการเลือกตั้งครั้งหน้า
				เราควรเลือก ‘ใคร’ หรือ ‘พรรคไหน’ ทำหน้าที่นี้
			</p>
			<br /><br />
			<h2 class="text-h5 font-kondolar font-bold">ที่มาของข้อมูล</h2>
			<ul class="flex list-disc flex-col gap-2 pl-4">
				<li>
					ข้อมูลการลงมติจาก
					<a
						class="hover:text-purple-1 underline"
						href="https://politigraph.wevis.info/"
						target="_blank"
						rel="noopener noreferrer"
						>ฐานข้อมูลการเมืองไทย</a
					>
					พัฒนาโดย <a
						class="hover:text-purple-1 underline"
						href="https://wevis.info/"
						target="_blank"
						rel="noopener noreferrer"
						>WeVis</a
					> กลุ่มเทคโนโลยีเพื่อประชาสังคม ซึ่งเก็บรวบรวมและวิเคราะห์จาก<a
						class="hover:text-purple-1 underline"
						href="https://msbis.parliament.go.th/ewtadmin/ewt/parliament_report/main.php?filename=index"
						target="_blank"
						rel="noopener noreferrer"
						>ระบบฐานข้อมูลรายงานและบันทึกการประชุม</a
					>
					สำนักงานเลขาธิการสภาผู้แทนราษฎร
				</li>
				<li>
					รายละเอียดร่างกฎหมายจาก
					<a
						class="hover:text-purple-1 underline"
						href="https://lis.parliament.go.th/index/search_advance.php"
						target="_blank"
						rel="noopener noreferrer"
						>ระบบสารสนเทศด้านนิติบัญญัติ</a
					>
					สำนักงานเลขาธิการสภาผู้แทนราษฎร
				</li>
			</ul>
			<br />
			<h3 class="text-b4 font-bold">การคัดเลือกประเด็น</h3>
			<p>
				ใช้ 10
				ร่างกฎหมายที่อยู่ในความสนใจของสาธารณชนและประเด็นที่มีการถกเถียงในเวทีสาธารณะในช่วง
				3 ปีที่ผ่านมา โดยคัดมาจากข่าวสื่อกระแสหลักและรายงานจากภาคประชาสังคม
			</p>
			<br />
			<h3 class="text-b4 font-bold">ข้อจำกัดของกระบวนการ</h3>
			<p>
				มติของพรรคต่อร่างกฎหมาย 10
				ฉบับนี้ไม่สามารถแทนวิสัยทัศน์เชิงนโยบายทั้งหมดของพรรคการเมืองได้
				และข้อมูลท่าทีพรรคอาจเปลี่ยนแปลงตามสถานการณ์ทางการเมืองในอนาคต
			</p>
			<br /><br />
			<h2 class="text-h5 font-kondolar font-bold">นโยบายการนำข้อมูลไปใช้ต่อ</h2>
			<p>
				ทางทีมมีความตั้งใจที่พัฒนาทุกโปรเจกต์ให้เป็น Open Source
				และเปิดข้อมูลเป็น Open Data ภายใต้ข้อตกลงในการใช้งาน
				<a
					href="https://wevis.info/terms-of-use/"
					target="_blank"
					rel="noopener noreferrer"
					class="hover:text-purple-1 underline"
					>Term of Use</a
				>
				<br />
				หากมีข้อสงสัยต้องการสอบถามเพิ่มเติม
				ประสงค์แจ้งเปลี่ยนแปลงหรือเพิ่มเติมข้อมูลเพื่อความถูกต้อง
				หรือมีข้อเสนอแนะใดๆ สามารถติดต่อได้ที่
				<span class="font-bold">team@wevis.info</span>
			</p>
			<br /><br />
			<h2 class="text-h5 font-kondolar font-bold">ทีมงานร่วมพัฒนา</h2>
			<div
				v-for="person in team"
				:key="person.role"
				class="flex flex-col gap-1"
			>
				<h3 class="text-b4 font-bold" style="margin-top: 1rem">
					{{ person.role }}
				</h3>
				<p>
					<template v-for="(name, index) in person.names">
						<a
							:href="person.links[index]"
							target="_blank"
							rel="noopener noreferrer"
							class="hover:text-purple-1 hover:underline"
						>
							{{ name }}
						</a>
						<span v-if="index < person.names.length - 1">, </span>
					</template>
				</p>
			</div>
			<br /><br />
			<h2 class="text-h5 font-kondolar font-bold">หมายเหตุ</h2>
			<p>
				<a
					href="https://wevis.info/"
					target="_blank"
					rel="noopener noreferrer"
					class="hover:text-purple-1 underline"
					>WeVis</a
				>
				ได้รับการสนับสนุนทุนในการดำเนินงานจาก
				<a
					href="https://www.ned.org/"
					target="_blank"
					rel="noopener noreferrer"
					class="hover:text-purple-1 underline"
					>National Endowment for Democracy (NED)</a
				>
				และ<a
					href="https://www.iri.org/"
					target="_blank"
					rel="noopener noreferrer"
					class="hover:text-purple-1 underline"
					>International Republican Institute</a
				>
				ซึ่งนำมาใช้เป็นต้นทุนในการรวมรวมข้อมูล ออกแบบ พัฒนาเว็บไซต์ ประสานงาน
				บริหารจัดการ ตลอดจนการจัดประชุมเพื่อดำเนินโครงการ
			</p>
		</div>
		<ElectionAboutActions
			dataUrl="https://docs.google.com/spreadsheets/d/1cg85RsWVrSTDgRsVMTsmbkABbDk8Y84kIU_SsRl_smQ/edit?usp=sharing"
		/>
		<ElectionSharer />
		<ElectionButton class="m-auto"
			><NuxtLink to="/">กลับไปหน้าแรก</NuxtLink></ElectionButton
		>
		<ElectionFooter />
	</div>
</template>

// apps/ballotready/src/app/about/page.tsx
'use client';
import {
	ElectionButton,
	ElectionFooter,
	ElectionSharer,
} from '@election/ui/react';

export default function AboutPage() {
	return (
		<div>
			<a
				href="/ballotready"
				className="flex items-center gap-[4px] p-[10px] hover:cursor-pointer"
			>
				<img
					className="w-[12px]"
					src="/ballotready/left-arrow.svg"
					alt="left-arrow"
				/>
				<p className="text-[14px]">กลับไปหน้าแรก</p>
			</a>
			<h1 className="font-kondolar text-h3 py-[72px] text-center font-bold">
				เกี่ยวกับโครงการ
			</h1>
			<div className="m-auto flex grid w-full max-w-[288px] flex-col justify-center gap-[50px] md:max-w-[650px] md:gap-[100px]">
				<div>
					<h2 className="font-kondolar text-h5 mb-[15px] font-bold md:mb-[30px]">
						เป้าหมาย
					</h2>
					<p className="mb-[20px]">
						การเลือกตั้งคือกลไกในระบอบประชาธิปไตยที่ประชาชนผู้ที่เป็นเจ้าของอำนาจจะต้องเลือก
						‘ผู้แทน’ ของตัวเองเข้าไปทำหน้าที่ในสภา
						จึงถือเป็นการตัดสินใจครั้งสำคัญว่าเราจะใช้อำนาจที่มีอยู่นี้เปลี่ยนแปลงสังคมและประเทศไปในทิศทางไหน
					</p>
					<p className="mb-[20px]">
						พวกเราทีม WeVis จึงจัดทำโปรเจกต์ ‘Ballot Ready เข้าคูหารอบนี้
						ต้องเลือกอะไรบ้าง ?’ ภายใต้แคมเปญ #WeVisElection69
						ที่จะช่วยให้คุณได้เตรียมตัวเลือกตั้งอย่างมั่นใจ
						โดยเริ่มจากทำความรู้จักผู้สมัคร สส.
						และพรรคการเมืองในตำบลหรือเขตเลือกตั้งของคุณว่ามีใครให้เลือกบ้าง
						พร้อมเข้าใจบัตรเลือกตั้งว่ามีกี่ใบและต้องกาอย่างไรให้ไม่เสียสิทธิ
					</p>
					<p>
						ก่อนเข้าคูหา #เลือกตั้ง69
						ขอชวนทุกคนศึกษาข้อมูลนี้เพื่อตัดสินใจมอบอำนาจให้กับ ‘ผู้แทน’
						ที่จะเข้าไปในรัฐสภาเพื่อใช้สิทธิและเสียงแทนเราอย่างแท้จริง
					</p>
				</div>
				<div>
					<h2 className="font-kondolar text-h5 mb-[15px] font-bold md:mb-[30px]">
						ที่มาของข้อมูล & ข้อจำกัด
					</h2>
					<p>
						ข้อมูลผู้สมัครสมาชิกสภาผู้แทนราษฎรแบบเขตและบัญชีรายชื่อ
						และรายชื่อบุคคลที่พรรคการเมืองมีมติจะเสนอสภาผู้แทนราษฎรพิจารณาให้ความเห็นชอบแต่งตั้งเป็นนายกรัฐมนตรี
						โดยคณะกรรมการการเลือกตั้ง
					</p>
				</div>
				<div>
					<h2 className="font-kondolar text-h5 mb-[15px] font-bold md:mb-[30px]">
						นโยบายการนำข้อมูลไปใช้ต่อ
					</h2>
					<p>
						ทางทีมมีความตั้งใจที่พัฒนาทุกโปรเจกต์ให้เป็น Open Source
						และเปิดข้อมูลเป็น Open Data ภายใต้ข้อตกลงในการใช้งาน (
						<a
							className="underline"
							href="https://wevis.info/terms-of-use/"
							target="_blank"
						>
							Terms of Use
						</a>
						)
						หากมีข้อสงสัยต้องการสอบถามเพิ่มเติมประสงค์แจ้งเปลี่ยนแปลงหรือเพิ่มเติมข้อมูลเพื่อความถูกต้อง
						หรือมีข้อเสนอแนะใด ๆ สามารถติดต่อได้ที่ team@wevis.info
					</p>
				</div>
				<div>
					<h2 className="font-kondolar text-h5 mb-[15px] font-bold md:mb-[30px]">
						อาสาสมัครร่วมพัฒนา
					</h2>
					<div className="mb-[15px] md:mb-[30px]">
						<p className="mb-[5px] font-bold md:mb-[10px]">พัฒนาเว็บไซต์</p>
						<p>ทรงพล นิลวงษ์</p>
					</div>
					<div className="mb-[15px] md:mb-[30px]">
						<p className="mb-[5px] font-bold md:mb-[10px]">ออกแบบ</p>
						<p>ชินธิป เอกก้านตรงษ์</p>
					</div>
					<div className="mb-[15px] md:mb-[30px]">
						<p className="mb-[5px] font-bold md:mb-[10px]">จัดการข้อมูล</p>
						<p>ดลภาค สุวรรณปัญญา</p>
					</div>
					<div className="mb-[15px] md:mb-[30px]">
						<p className="mb-[5px] font-bold md:mb-[10px]">
							สืบค้นและรวบรวมข้อมูล
						</p>
						<p>อาลาวีย์ วาแม</p>
					</div>
					<div>
						<p className="mb-[5px] font-bold md:mb-[10px]">บรรณาธิการ</p>
						<p>ธนิสรา เรืองเดช</p>
						<p>น้ําใส ศุภวงศ์</p>
					</div>
				</div>
				<div>
					<h2 className="font-kondolar text-h5 mb-[15px] font-bold md:mb-[30px]">
						หมายเหตุ
					</h2>
					<p>
						<a className="underline" href="https://wevis.info/" target="_blank">
							WeVis
						</a>
						 ได้รับการสนับสนุนทุนในการดำเนินงานจาก{' '}
						<a
							className="underline"
							href="https://www.ned.org/"
							target="_blank"
						>
							National Endowment for Democracy (NED)
						</a>
						 และ
						<a
							className="underline"
							href="https://www.iri.org/"
							target="_blank"
						>
							International Republican Institute
						</a>
						ซึ่งนำมาใช้เป็นต้นทุนในการรวมรวมข้อมูล ออกแบบ พัฒนาเว็บไซต์
						ประสานงาน บริหารจัดการ ตลอดจนการจัดประชุมเพื่อดำเนินโครงการ
					</p>
				</div>
			</div>
			<div className="flex flex-col items-center justify-center gap-[10px] py-[20px] md:flex-row md:py-[50px]">
				<a
					href="https://drive.google.com/drive/folders/171KdzhbsE-x2k9HNFioWBnnHVUk7xXEN"
					target="_blank"
				>
					<ElectionButton className="typo-h9 font-kondolar self-center text-[14px] font-bold">
						<div className="flex w-[132px] gap-[8px]">
							<img src="/ballotready/download-icon.svg" alt="download-icon" />{' '}
							ดาวน์โหลดข้อมูล
						</div>
					</ElectionButton>
				</a>
				<a
					href="https://airtable.com/appsowPzCsRLmUvNx/shryu4errnlj1LWsM"
					target="_blank"
				>
					<ElectionButton className="typo-h9 font-kondolar w-[180px] self-center text-[14px] font-bold">
						<div className="flex w-[132px] gap-[8px]">
							<img src="/ballotready/envelop-icon.svg" alt="envelop-icon" />{' '}
							Feedback
						</div>
					</ElectionButton>
				</a>
				<a
					href="https://github.com/wevisdemo/thailand-election-2026"
					target="_blank"
				>
					<ElectionButton className="typo-h9 font-kondolar w-[180px] self-center text-[14px] font-bold">
						<div className="flex w-[132px] gap-[8px]">
							<img src="/ballotready/github-icon.svg" alt="github-icon" /> View
							on Github
						</div>
					</ElectionButton>
				</a>
			</div>
			<ElectionSharer className="py-[40px]" />
			<ElectionFooter />
		</div>
	);
}
